# Add application configuration variables here, as shown below.
#

  AWS_ACCESS_KEY_ID: AKIAJIUI7TGNMNEEMR5Q
  AWS_SECRET_ACCESS_KEY: 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
  AWS_BUCKET: Reserver

# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
