development:
  adapter: postgresql
  database: reserveDB_dev
  username: brad
  password: secret
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: reserveDB_test
  username: brad
  password: secret
  pool: 5
  timeout: 5000