
development:
  adapter: postgresql
  encoding: unicode
  database: reservester_development
  username: root
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: reservester_test
  username: root
  password: 
  pool: 5
  timeout: 5000

