
development:
  adapter: postgresql
  database: reservester_development
  username: root
  password: password
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: reservester_test
  username: root
  password: password
  pool: 5
  timeout: 5000

